{% set version = "0.0.8" %}

package:
    name: xray-vision
    version: {{ version }}

source:
    url: https://github.com/Nikea/xray-vision/archive/v{{ version }}.tar.gz
    fn: xray-vision-v{{ version }}.tar.gz
    sha256: a5a1cb0b638d9d712ad1ce129fc26a61149a145f8c4cbaa2711f181115f34bb6

build:
    noarch: python
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - numpy
        - matplotlib
        - pyqt
        - python
        - six

test:
    imports:
        - xray_vision
        - xray_vision.backend
        - xray_vision.backend.mpl
        - xray_vision.mask
        - xray_vision.messenger
        - xray_vision.messenger.mpl
        - xray_vision.mpl_plotting
        - xray_vision.qt_widgets
        - xray_vision.utils

about:
    home: https://github.com/Nikea/xray-vision
    license: 3-Clause BSD
    summary: Visualization widgets and plotting helpers targeted at X-Ray Sciences

extra:
    recipe-maintainers:
        - ericdill
        - licode
        - tacaswell
        - CJ-Wright
