travis:
  secure:
    BINSTAR_TOKEN: bTCS8dOKjpa3s62t8Rj5ZoHcY9hFJcGOHm7Dkzs6p+C9ICevOQ067HOdfG7Gpy9BiIiWaVny+YZdeeqyC8oXeVcaVOiIAsrGLYzuPNnDuwMXy1rsqLlIZr7fxfNaMGQmdL8k7A8kz4IQQQ/s6LnuQB3SNi3FfibWoFNjdXoUhPHBKtb7YTL7q43EfyLui2L7OtS+4GeTvpoWrdB+tOyfpS6a4SaeU2nN18+Bwldev7j52waj+LhxfXgvwu/eCvygTFvu4v5vXPSHHPA5ekDHognYKt6fjXw9TFiUbV7y6ljOGhmQrQRRH7l5IpGqe9ioQxLrbpyc898JbmnFmrPzWmyA4ygcvSxQxOsA1CIQQqkw+6jjvrrb9kE/hhOu3K7FtolrvX4K24NaFRGvUPPwTAri4KZP8yxOJrTlTm/Mv6A4cpsS6zIpVuOijvNBVnTbn6v1vxF1LWEZs3TP1Xwq3BFPOdUTEMVcT1nikCwTM9ekmwcDaTnpthX0Wg3SwJhnBRCtf9+4sZeNh2VtaaJA7BWpkYW0kixy8qcYTcn4dKO40gGjSTLq0E4WFCddo5anv2lsNGdsHkC+rnzaVJutS9aROdYX4ZAIDWTrc3vuLuIZGaFvBDAtmPrReebbBC3m/91l/3bcbKuW6zwq7ArKO9S+cyZeWcao+pD/FMwP+l4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
